-- JOIN QUERY syntax chara join korah jai 2 tah table er column keh avbhe
SELECT EMPLOYEES.FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;
-- JOIN QUERY SYNTAX USE KOREH JOIN KORAR UPAI
SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID