/* Niche amrah 3 tah student table create korlam just constraint jeh multiple way teh 
declare korah jai setah dekhar jonno 
  */
CREATE TABLE STUDENT 
(
NAME VARCHAR (50) NOT NULL,
ROLL CHAR (4) PRIMARY KEY,
EMAIL VARCHAR(50) UNIQUE,
ADDRESS VARCHAR(100),
AGE INT CHECK (AGE>10)
);

CREATE TABLE STUDENT 
(
NAME VARCHAR (50) NOT NULL,
ROLL CHAR(4) ,
EMAIL VARCHAR (50),
ADDRESS VARCHAR (100),
AGE INT,
PRIMARY KEY (ROLL),
UNIQUE (EMAIL),
CHECK (AGE >10)
);

CREATE TABLE STUDENT 
(
NAME VARCHAR (50) NOT NULL,
ROLL CHAR(4),
EMAIL VARCHAR (50),
ADDRESS VARCHAR (100),
AGE INT,
CONSTRAINT PK_RULE PRIMARY KEY (ROLL),
CONSTRAINT UNIQUE_RULE UNIQUE (EMAIL),
CONSTRAINT CHEKING_RULE CHECK (AGE >10)
);

CREATE TABLE LIBRARY
(
BOOKnAME VARCHAR (50) ,
WHO_HIRED_R0LL CHAR (4),
CONSTRAINT PRIMARY KEY(BOOKnAME),
-- BELOW LINE PROVIDE SYNTAX OF FOREIGN KEY
FOREIGN KEY (WHO_HIRED_R0LL) REFERENCES STUDENT (ROLL)
);

CREATE TABLE COURSE
( UNIVERSITY_NAME VARCHAR (50),
COURSE_NAME VARCHAR (60),
CREDIT INT,
-- BELOW LINE PROVIDE SYNTAX OF COMPOSITE PRIMARY KEY
PRIMARY KEY (UNIVERSITY_NAME,COURSE_NAME)
);

