use programminghero;
 CREATE Table Student
 ( 
  Rool CHAR(4)PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  Email VARCHAR(50) UNIQUE,
  Adress VARCHAR(50),
 Age INT CHECK (Age>10)
 );
 INSERT INTO Student (Rool,Name,Email,Adress,Age) VALUES ('001','ARMAN SARDAR','ARMAN@GMAIL.COM','CHANDPUR',11);
  INSERT INTO Student (Rool,Name,Email,Age) VALUES ('003','ARMAN SARDAR','BRSA@GMAIL.COM',11);
 CREATE Table Student
 ( 
  Rool CHAR(4),
  Name VARCHAR(50),
  Email VARCHAR(50),
  Adress VARCHAR(50),
 Age INT(3),
 CONSTRAINT PK_RULES PRIMARY KEY(Rool),
 CONSTRAINT UNIQUE_RULES UNIQUE (Email),
 CONSTRAINT CHECKING_RULE CHECK (Age >10)
 );
 
 CREATE Table Student
 ( 
  Rool CHAR(4),
  Name VARCHAR(50),
  Email VARCHAR(50),
  Adress VARCHAR(50),
 Age INT(3),
 PRIMARY KEY (Rool),
 UNIQUE (EmaiL),
 CHECK (Age>10)
 );
 
 
 CREATE TABLE Library
 ( BOOK_NAME VARCHAR (100),
 WHOHIRED_ROOL VARCHAR(4),
 FOREIGN KEY (WHOHIRED_ROOL) REFERENCES Student(Rool)
 );

-- BELOW LINE EXAMPLE fOR  COMPOSITE PRIMARY KEY 
CREATE TABLE COURSE
(
COURSE_NAME VARCHAR (50),
UNIVERSITY_NAME VARCHAR (59),
CREDIT INT,
PRIMARY KEY(COURSE_NAME, UNIVERSITY_NAME)
);