 USE programminghero;
 CREATE TABLE NEw_student
(
NAME VARCHAR (100),
Roll CHAR(4) PRIMARY KEY,
CLass INT,
Age INT
);

INSERT INTO Student (Name,Roll,Class,Age) VALUES ('ARMAN SARDAR','0001',10,11);
CREATE TABLE Library
( BookName VARCHAR(50),
WhoHired_Roll CHAR(4),
FOREIGN KEY (Whohired_Roll) REFERENCES NEw_student(Roll)
);

/*CREATE TABLE Fees
(
FEE_AMOUNT INT,
STUDENT_ROLL CHAR(4),
FOREIGN KEY (STUDENT_ROLL) REFERENCES Student(Roll)
);*/

